<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-list"></span> <?php $this->show('Menu'); ?>
      </button>

      <div class="dropdown-menu">
         <a class="dropdown-item" href="<?php echo $this->url('Qa:Admin:Qa@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new pair'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Qa:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a>
         <div class="dropdown-divider"></div>
         <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
         <?php if (!empty($pairs)):?>
         <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('Qa:Admin:Qa@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
         <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Qa:Admin:Qa@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php else: ?>
         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php endif; ?>
      </div>
    </div>

    <?php $this->loadPartial('items-per-page', array('caption' => 'Questions and Answers')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($pairs, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'question'
                    ),

                    array(
                        'column' => 'questioner'
                    ),
                    
                    array(
                        'column' => 'answerer'
                    ),
                    
                    array(
                        'column' => 'ip',
                        'label' => 'IP'
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($qa){
                            return Element::checkbox(sprintf('published[%s]', $qa->getId()), $qa->getPublished());
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($qa){
                        return Icon::edit(
                            $this->url('Qa:Admin:Qa@editAction', $qa->getId()),
                            $this->translate('Edit this pair')
                        );
                    },

                    'remove' => function($qa){
                        return Icon::remove(
                            $this->url('Qa:Admin:Qa@deleteAction', $qa->getId()),
                            $this->translate('Remove this pair')
                        );
                    }
                )
            ))); ?>
            
            <?php if (empty($pairs)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pairs'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>
