<?php

use Krystal\Widget\GridWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-list"></span> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Qa:Admin:Qa@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add a pair'); ?></a></li>
		 <li><a href="<?php echo $this->url('Qa:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($pairs)):?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Qa:Admin:Qa@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Qa:Admin:Qa@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Questions and Answers')); ?>

<form>
	<div class="table-responsive">
        <?= $this->widget(new GridWidget($pairs, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'question'
                ),

                array(
                    'column' => 'questioner'
                ),
                
                array(
                    'column' => 'answerer'
                ),
                
                array(
                    'column' => 'ip',
                    'label' => 'IP'
                ),

                array(
                    'column' => 'published',
                    'value' => function($qa){
                        return Element::checkbox(sprintf('published[%s]', $qa->getId()), $qa->getPublished());
                    }
                )
            ),

            'actions' => array(
                'edit' => function($qa){
                    return Icon::edit(
                        $this->url('Qa:Admin:Qa@editAction', $qa->getId()),
                        $this->translate('Edit this pair')
                    );
                },

                'remove' => function($qa){
                    return Icon::remove(
                        $this->url('Qa:Admin:Qa@deleteAction', $qa->getId()),
                        $this->translate('Remove this pair')
                    );
                }
            )
        ))); ?>
		
		<?php if (empty($pairs)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pairs'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
