<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="config" autocomplete="off">
    <div class="form-group">
        <label class="col-lg-10 control-label"><?php $this->show('Per page count'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?php echo Element::number('config[per_page_count]', $config->getPerPageCount(), array('class' => 'form-control')); ?>
                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            </div>

            <span class="help-block"><?php $this->show('Amount of pairs to be displayed per page'); ?></span>
        </div>
    </div>

    <div class="actions">
        <button data-button="save" data-url="<?php echo $this->url('Qa:Admin:Config@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
        <button data-button="cancel" data-url="<?php echo $this->url('Qa:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Cancel'); ?></button>
    </div>
</form>