<?php

use Krystal\Form\Element;

?>

<form data-group="qa">

	<div class="well clearfix">
        <?php echo Element::hidden('qa[id]', $qa->getId()); ?>
        
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Question'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('qa[question]', $qa->getQuestion(), array('class' => 'form-control', 'placeholder' => $this->translate('Type the question'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Questioner'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('qa[questioner]', $qa->getQuestioner(), array('class' => 'form-control', 'placeholder' => $this->translate('Person who asked this question'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Answerer'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('qa[answerer]', $qa->getAnswerer(), array('class' => 'form-control', 'placeholder' => $this->translate('Person who answered this question'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Answer'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('qa[answer]', $qa->getAnswer()); ?>
			</div>
		</div>
		
		<div class="options">
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Date asked'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
                        <?php echo Element::text('qa[date_asked]', date($timeFormat, $qa->getTimestampAsked()), array('class' => 'form-control', 'placeholder' => $this->translate('Date of the question'))); ?>
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Date answered'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
                        <?php echo Element::text('qa[date_answered]', date($timeFormat, $qa->getTimestampAnswered()), array('class' => 'form-control', 'placeholder' => $this->translate('Date of the answer'))); ?>
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
                    <?php echo Element::checkbox('qa[published]', $qa->getPublished(), array('class' => 'form-control')); ?>
				</div>
			</div>
		</div>
	</div>
	
	<?php if (!$qa->getId()): ?>

	<button data-button="add" data-back-url="<?php echo $this->url('Qa:Admin:Qa@editAction', null); ?>" data-url="<?php echo $this->url('Qa:Admin:Qa@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Qa:Admin:Qa@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
    <?php else: ?>

	<button data-button="save" data-url="<?php echo $this->url('Qa:Admin:Qa@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Qa:Admin:Qa@addAction'); ?>" data-url="<?php echo $this->url('Qa:Admin:Qa@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

	<?php endif; ?>

	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" data-url="<?php echo $this->url('Qa:Admin:Qa@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>
